### ISSUE TITLE
Theme autodetect not working

### ISSUE THREAD

**Issue by T3sT3ro** [melianmiko/OpenFreebuds#27]
I'm on ubuntu 22.04 with dark OS settings and I just installed the `0.13.3-2-all.deb` version of the package, and the theme auto-detection didn't work. The tray icon used black variant instead of white on a black taskbar, making it invisible. I changed the icon theme manually so it's a minor thing, but I was confused in the beginning, not sure if program crashed on startup because I didn't see the icon :sweat_smile:. The settings window also used light theme when auto-detect was set.

**Comment by melianmiko** [comment]
After research, found that due to huge diversity across Linux desktop environments, there's no proper way to exactly detect system status bar color, only thing that app can exactly identify is their own window color scheme.

So, issue looks to be unsolvable, if system panel color didn't match with window background color, auto-detect will fail.

**Comment by melianmiko** [comment]
Settings dialog theme will be fixed in next release, due to migration to Qt, it will always follow system settings.
